### ISSUE TITLE
Wrong command for virtual conda enviroment installation

### ISSUE THREAD

**Issue by patricebender** [zaratropia/self-driving-car-sim-iws#1]
Reproduce:
$ conda create env -f environment.yml
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: environment.yml

use this command instead:
$ conda env create -f environment.yml

**Comment by zaratropia** [comment]
Fixed https://github.com/zaratropia/self-driving-car-sim-iws/commit/7eeddf14e02e38f22798b029e4fdc41f46222bcd.
